# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20180711_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location_name',
            new_name='location',
        ),
    ]
